name: Build Subproject 3

on:
  push:
    branches: [ "master" ]
    paths:
      - 'subproject-3/**'
      - '!settings.gradle'

permissions:
  contents: read

jobs:
  build:
    uses: Jonathing/SharedActions/.github/workflows/gradle.yml@feat/jonathing/subproject-versioning-test
    with:
      subproject: "subproject-3"
      tag_prefix: subproject-3
      java: 17
      gradle_tasks: ":subproject-3:build"
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}